### ISSUE TITLE
[FE] 프로젝트 환경설정

### ISSUE THREAD

**Issue by choisohyun** [codesquad-member-2020/baseball-09#3]
cra를 쓰지 않고 프로젝트 환경설정을 진행해 본다.

```
┌ react
├ react route
├ typescript
├ babel
├ dotenv
├ craco
└ eslint
```

**Comment by crongro** [comment]
typescript 설정! 
적용하시고, 부분적으로 ts코드를 적용해보시면 될 듯. 


carco 가 꼭 필요한가요? 
CRA 기반의 환경설정에 대해서 잘 이해(이 구조가 어떻게 생겨먹은거지?)하신 후 
나중에 사용해도 될 듯.
물론 craco의 장점에 대해서 분명 느끼는 부분이 있다면 사용해도 OK!

**Comment by choisohyun** [comment]
@crongro craco 대신에 webpack config에서 alias 로 설정해 두는 방법으로 진행했습니다~!

**Comment by choisohyun** [comment]
## 최종 환경

```
- cra를 대체하여 직접 환경설정 진행
- 타입스크립트 활용
- 바벨 활용
- 스타일드 컴포넌트 라이브러리 추가
- dotenv 사용
```
